// Single source of truth for the main nav, the footer's list, and each
// page's <head> metadata. Edit this file (and src/pages/*.html for
// content) — public/*.html is generated by scripts/build.mjs and should
// not be hand-edited.

export const NAV = [
  { href: 'index.html', label: 'Home' },
  { href: 'rules.html', label: 'The Rules' },
  { href: 'https://github.com/magicobject/MrWrightsRules', label: 'GitHub', external: true },
];

export const FOOTER_NAV = [
  { href: 'index.html', label: 'Home' },
  { href: 'rules.html', label: 'The Rules' },
];

export const PAGES = [
  {
    slug: 'index',
    title: "Mr Wright's Rules — Development &amp; Testing Principles for Software Developers",
    description: 'Development and testing principles for software developers, honed over 40 years of professional practice.',
    active: 'index.html',
    header: true,
  },
  {
    slug: 'rules',
    title: "The Rules — Mr Wright's Rules",
    description: 'Seven rules that condense 40 years of software development experience: no shortcuts, first-class code, coding for other people, avoiding stream-of-subconsciousness programming, security, and testing.',
    active: 'rules.html',
    header: true,
  },
  {
    slug: 'rule-1-there-are-no-shortcuts',
    title: 'Rule 1: There Are No Shortcuts',
    description: 'Technical debt is unavoidable, but good professional practice is the fastest path to delivery, not the slowest.',
    active: null,
    header: true,
  },
  {
    slug: 'rule-2-all-code-is-first-class-code',
    title: 'Rule 2: All Code Is First-Class Code',
    description: "Code exists primarily to convey a technical solution to other people's minds. Test code deserves the same quality as application code.",
    active: null,
    header: true,
  },
  {
    slug: 'rule-3-code-for-other-people',
    title: 'Rule 3: Code for Other People, Not Just for the Solution',
    description: 'Programming with intent, DocBlocks, immutability, and the practical habits that make code readable by the next person.',
    active: null,
    header: true,
  },
  {
    slug: 'rule-4-avoid-stream-of-subconsciousness-programming',
    title: 'Rule 4: Avoid Stream of Subconsciousness Programming',
    description: 'Pouring thoughts into the editor with no prior consideration of intent leaves a codebase no one can safely change.',
    active: null,
    header: true,
  },
  {
    slug: 'rule-5-security-is-your-responsibility',
    title: 'Rule 5: Security Is Your Responsibility',
    description: 'Security is the primary non-functional requirement, and every developer is responsible for it.',
    active: null,
    header: true,
  },
  {
    slug: 'rule-6-always-test-first',
    title: 'Rule 6: Always Test First',
    description: 'Testing is nearly impossible to reverse-engineer well. Write it first, so it is always in place, protecting your code, your application and your customer.',
    active: null,
    header: true,
  },
  {
    slug: 'rule-7-test-functionality-not-implementation',
    title: 'Rule 7: Test Functionality, Not Implementation',
    description: 'Test the contract your code makes with its caller, not its internal mechanics, so the implementation is free to change without ever touching the test suite.',
    active: null,
    header: true,
  },
  {
    slug: '404',
    title: "Page Not Found — Mr Wright's Rules",
    description: "This page couldn't be found. Find your way back to the rules from the home page.",
    active: null,
    header: false,
    canonical: false,
    robots: 'noindex',
  },
];
